services:
  app:
    image: node:latest
    working_dir: /app
    volumes:
      - .:/app
    command: "npm start"
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
